# ------------
# | Wrappers |
# ------------
[tasks.fmt]
command = "cargo"
args = ["fmt"]
private = true

[tasks.check]
command = "cargo"
args = ["check"]
private = true

[tasks.clippy]
command = "cargo"
args = ["clippy"]
private = true

# -------------
# | Executors |
# -------------
[tasks.checkf]
dependencies = ["fmt", "check"]

[tasks.checkfc]
dependencies = ["fmt", "check", "clippy"]
